version: "3"
services:
  app:
    container_name: containerize_app_1
    restart: always
    build:
     context: ./app
     dockerfile: Dockerfile
    ports:
     - "8000:8000"
    command: gunicorn -w 1 -b :8000 server:app

  nginx:
    container_name: containerize_nginx_1
    restart: always
    build:
     context:  ./nginx
     dockerfile: Dockerfile
    volumes:
            - ssl_certificates:/nginx/files/

    ports:
     - 80:80
     - 443:443
    depends_on:
     - app
volumes:
  ssl_certificates:
    driver: local
